#!/usr/bin/env bash

# setup-broker.sh
# Description: This script will install a Secure Mosquitto MQTT Broker on a Ubuntu / Debian system.
# Verson: 1.0.0
# Version_Date: 2024-03-26
# Author: John Haverlack (jehaverlack@alaska.edu)
# License: MIT (Proposed/Pending) / UAF Only
# Source: https://github.com/acep-uaf/camio-mqtts

# This script is intended to be idemopotent.  It can be run multiple times without causing issues.

# Check if dependancy binaries are installed.
req_binaries=(apt awk cat cut date df egrep grep jq lsblk mount sed stat tail tr uname uptime wc which)
for i in "${req_binaries[@]}"; do
  if ! which $i > /dev/null 2>&1; then
    echo "Error: $i binary not found or not executable.  Please install $i"
    exit 1
  fi
done

# Verify that this script is being run as root.
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root."
    exit 1
fi

# Determine the directory full path where this seal-os.sh file is located.
rundir=$(realpath $(dirname $0))

# Check to see if the losd-lib.sh file exists and is readable.
if [ ! -r $rundir/losd/losd-lib.sh ]; then
  echo "Error: $rundir/losd/losd-lib.sh file not found or not readable."
  exit 1
fi

# Defined supported OS
supported_os=("Ubuntu" "Debian")

# Source the losd-lib.sh file.
source $rundir/losd/losd-lib.sh

losd_json=$(losd)

host_name=$(echo $losd_json | jq '.HOST.HOSTNAME' | sed -r 's/"//g')
os_name=$(echo $losd_json | jq '.DISTRO.NAME' | sed -r 's/"//g')
os_version=$(echo $losd_json | jq '.DISTRO.VERSION' | sed -r 's/"//g')
hw_platform=$(echo $losd_json | jq '.HARDWARE.HOSTNAMECTL.Chassis' | tr -dc '[:print:]' | sed -r 's/\s//g' | sed -r 's/"//g')
ip_addr=$(echo $losd_json | jq .HARDWARE.NETWORK | jq -r '.[] | select(.INTERFACE != "lo") | .IPV4_ADDR')

# Check to see if the losd-lib.sh file exists and is readable.
if [ ! -r $rundir/conf/mqtt.json ]; then
  echo "Error: $rundir/losd/losd-lib.sh file not found or not readable."
  exit 1
fi

# Read the mqtt.json file
mqtt_json=$(cat $rundir/conf/mqtt.json | jq)

# Extract MQTT Vars
mqtt_conf_file=$(echo $mqtt_json | jq '.CONFIG.CONF_FILE' | sed -r 's/"//g')

## Defaults
mqtt_allow_anon=true
mqtt_host=$(echo $mqtt_json | jq '.BROKER.HOST' | sed -r 's/"//g')
mqtt_port=$(echo $mqtt_json | jq '.BROKER.PORT' | sed -r 's/"//g')

mqtt_tls_status=$(echo $mqtt_json | jq '.TLS.ENABLED' | sed -r 's/"//g')
# if mqtt_tls_status is true, then set mqtt_tls_status to "Enabled", else set it to "Disabled"
if [ $mqtt_tls_status ]; then
  mqtt_tls_ca=$(echo $mqtt_json | jq '.TLS.CA_CERT' | sed -r 's/"//g')
  mqtt_tls_cert=$(echo $mqtt_json | jq '.TLS.CERTIFICATE' | sed -r 's/"//g')
  mqtt_tls_key=$(echo $mqtt_json | jq '.TLS.PRIVATE_KEY' | sed -r 's/"//g')
  mqtt_host=$(echo $mqtt_json | jq '.TLS.HOST' | sed -r 's/"//g')
  mqtt_port=$(echo $mqtt_json | jq '.TLS.PORT' | sed -r 's/"//g')
fi


mqtt_auth_status=$(echo $mqtt_json | jq '.AUTH.ENABLED' | sed -r 's/"//g')
# if mqtt_auth_status is true, then set mqtt_auth_status to "Enabled", else set it to "Disabled"
if [ $mqtt_auth_status ]; then
  mqtt_allow_anon=false
  mqtt_passwd_file=$(echo $mqtt_json | jq '.CONFIG.PASSWD_FILE' | sed -r 's/"//g')
  mqtt_user=$(echo $mqtt_json | jq '.AUTH.USERS[0]' | sed -r 's/"//g')
fi


echo ""
echo "Host Name:         $host_name"
echo "OS Name:           $os_name"
echo "OS Version:        $os_version"
echo "Hardware Platform: $hw_platform"
echo "IP Address:        $ip_addr"
echo ""

echo "MQTT Broker Host:  $mqtt_host"
echo "MQTT Broker Port:  $mqtt_port"
echo "MQTT TLS Status:   $mqtt_tls_status"
echo "MQTT Auth Status:  $mqtt_auth_status"
echo ""

# Check if the OS is supported
if [[ ! " ${supported_os[@]} " =~ " ${os_name} " ]]; then
    echo "ERROR: Unsupported OS detected: $os_name $os_version"
    exit 1
fi

echo ""
echo "WARNING:"
echo "This script [setup-broker.sh] will install and configure a TLS secured Mosquitto MQTT Broker."
read -p "Continue [y/N]:" ans
echo ""

if [[ "$ans" != "y" && "$ans" != "Y" ]]; then
    echo "INFO: Aborting Script."
    exit 1
fi

# ==================== BEGIN MQTTS SETUP SCRIPT ====================


# Install the necessary packages
apt update
apt install -y mosquitto mosquitto-clients ufw


# Generate mqtt_conf_file
mqtt_config=""
mqtt_config+="# This file was generated by the setup-broker.sh script. See: https://github.com/acep-uaf/camio-mqtts\n"
mqtt_config+="# Mosquitto MQTT Broker Configuration File\n"
mqtt_config+="\n\n"
mqtt_config+="listener $mqtt_port $mqtt_host"
mqtt_config+="\n\n"
mqtt_config+="allow_anonymous $mqtt_allow_anon"
mqtt_config+="\n\n"

if [ $mqtt_tls_status ]; then
    mqtt_config+="cafile $mqtt_tls_ca"
    mqtt_config+="\n"
    mqtt_config+="certfile $mqtt_tls_cert"
    mqtt_config+="\n"
    mqtt_config+="keyfile $mqtt_tls_key"
    mqtt_config+="\n\n"
fi

if [ $mqtt_auth_status ]; then
    mqtt_config+="password_file $mqtt_passwd_file"
    mqtt_config+="\n\n"
fi

echo "DEBUG: mqtt_config"
echo -e "$mqtt_config"

#echo -e $mqtt_config > $mqtt_conf_file

# Configure MQTT Passwords
# if ! /etc/mosquitto/passwd
# if [ ! -f /etc/mosquitto/passwd ]; then
#     mosquitto_passwd -c /etc/mosquitto/passwd $mqtt_user
# fi


# Create a self-signed certificate

# Create a directory to store the certificates


# Configure the Mosquitto Broker

# Configure the UFW Firewall

# Enable and Start the Mosquitto Broker

